[workspace]
resolver = "2"
members = ["extism-maturin", "manifest", "runtime", "libextism", "convert", "convert-macros"]
exclude = ["kernel"]

[workspace.package]
edition = "2021"
authors = ["The Extism Authors", "oss@extism.org"]
license = "BSD-3-Clause"
homepage = "https://extism.org"
repository = "https://github.com/arthurianresolve/extism-with-wasmtime46"
version = "1.30.0+wasmtime46"

[workspace.dependencies]
extism = { path = "./runtime", version = "1.30.0" }
extism-convert = { path = "./convert", version = "1.30.0" }
extism-convert-macros = { path = "./convert-macros", version = "1.30.0" }
extism-manifest = { path = "./manifest", version = "1.30.0" }
